### ISSUE TITLE
crash in DEFAULT_ALLOC

### ISSUE THREAD

**Issue by lfnoise** [goldsteinn/hashtable_test#2]
On Mac OS the call to `aligned_alloc` returns NULL. Subsequently, the index into it crashes.
cppreference says of `aligned_alloc`: "The size parameter must be an integral multiple of alignment." And apparently, Mac OS enforces that.
But `size * sizeof(fht_chunk<K, V>) + 1` is 2113 bytes, which is not a multiple of `FHT_TAGS_PER_CLINE`  (64).

**Comment by goldsteinn** [comment]
fixed in [here](https://github.com/goldsteinn/hashtable_test/commit/a6b6c8eda040fc44c9a58bdd3114a22f36109155)
